services:
  db:
    ports:
      - "127.0.0.1:5432:5432"
  api:
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      APP_ENV: development
      COOKIE_SECURE: "false"
  web:
    ports:
      - "127.0.0.1:3000:3000"
