import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790797071549 implements MigrationInterface {
    name = 'InitialSchema1790797071549'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Extensions & sequences (must exist before tables that reference them in defaults)
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pg_trgm"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "patient_code_seq" START 1`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "kiosk_request_number_seq" START 1001`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "receipt_number_seq" START 1`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying(150) NOT NULL, "name_ru" character varying(150), "code" character varying(20) NOT NULL, "queue_prefix" character varying(3) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_departments_code" ON "departments" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_departments_queue_prefix" ON "departments" ("queue_prefix") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "department_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "name_ru" character varying(200), "code" character varying(30) NOT NULL, "price" numeric(14,2) NOT NULL, "duration_minutes" integer NOT NULL DEFAULT '15', "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_services_code" ON "services" ("code") `);
        await queryRunner.query(`CREATE INDEX "idx_services_department_active" ON "services" ("department_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "doctor_services" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "doctor_id" uuid NOT NULL, "service_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_576dd4346e554b2ba3f27878be8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_doctor_services_service" ON "doctor_services" ("service_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_doctor_services_pair" ON "doctor_services" ("doctor_id", "service_id") `);
        await queryRunner.query(`CREATE TABLE "doctors" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "specialty" character varying(150) NOT NULL, "room_number" character varying(20) NOT NULL, "work_schedule" jsonb NOT NULL DEFAULT '{}'::jsonb, "is_available" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_653c27d1b10652eb0c7bbbc4427" UNIQUE ("user_id"), CONSTRAINT "REL_653c27d1b10652eb0c7bbbc442" UNIQUE ("user_id"), CONSTRAINT "PK_8207e7889b50ee3695c2b8154ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role" AS ENUM('ADMIN', 'DOCTOR', 'REGISTRAR', 'KIOSK')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED')`);
        await queryRunner.query(`CREATE TYPE "public"."gender" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "login" character varying(64) NOT NULL, "password_hash" character varying(100) NOT NULL, "role" "public"."user_role" NOT NULL, "status" "public"."user_status" NOT NULL DEFAULT 'ACTIVE', "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "middle_name" character varying(100), "birth_date" date, "gender" "public"."gender", "phone" character varying(32), "email" character varying(150), "address" character varying(500), "profession" character varying(150), "avatar" text, "must_change_password" boolean NOT NULL DEFAULT false, "last_login_at" TIMESTAMP WITH TIME ZONE, "password_changed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_users_login" ON "users" ("login") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role_status" ON "users" ("role", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_action" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGE', 'PAYMENT', 'REFUND', 'CANCEL', 'QUEUE_CALL', 'QUEUE_STATUS', 'PRICE_CHANGE', 'EXPORT')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid, "action" "public"."audit_action" NOT NULL, "module" character varying(50) NOT NULL, "entity" character varying(50) NOT NULL, "entity_id" character varying(64), "old_value" jsonb, "new_value" jsonb, "description" character varying(500), "ip" character varying(64), "user_agent" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_module_action" ON "audit_logs" ("module", "action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user" ON "audit_logs" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "replaced_by_id" uuid, "login_history_id" uuid, "ip" character varying(64), "user_agent" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."kiosk_request_status" AS ENUM('NEW', 'IN_REVIEW', 'PROCESSED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "kiosk_requests" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "number" integer NOT NULL DEFAULT nextval('kiosk_request_number_seq'), "status" "public"."kiosk_request_status" NOT NULL DEFAULT 'NEW', "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "middle_name" character varying(100), "phone" character varying(32) NOT NULL, "birth_date" date, "gender" "public"."gender", "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "kiosk_user_id" uuid, "claimed_by_id" uuid, "claimed_at" TIMESTAMP WITH TIME ZONE, "processed_by_id" uuid, "processed_at" TIMESTAMP WITH TIME ZONE, "payment_id" uuid, "cancel_reason" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b637202848542dc0d397a440849" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_kiosk_requests_number" ON "kiosk_requests" ("number") `);
        await queryRunner.query(`CREATE INDEX "idx_kiosk_requests_status_created" ON "kiosk_requests" ("status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "kiosk_request_items" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "kiosk_request_id" uuid NOT NULL, "service_id" uuid NOT NULL, "service_name" character varying(200) NOT NULL, "price" numeric(14,2) NOT NULL, CONSTRAINT "PK_be1391e88553398ff6c0859e830" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_kiosk_request_items_request" ON "kiosk_request_items" ("kiosk_request_id") `);
        await queryRunner.query(`CREATE TABLE "login_history" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid, "login_attempt" character varying(100) NOT NULL, "success" boolean NOT NULL, "failure_reason" character varying(100), "ip" character varying(64), "user_agent" character varying(500), "browser" character varying(100), "os" character varying(100), "device" character varying(20), "login_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "logout_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_fe377f36d49c39547cb6b9f0727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_login_history_login_at" ON "login_history" ("login_at") `);
        await queryRunner.query(`CREATE INDEX "idx_login_history_user_login_at" ON "login_history" ("user_id", "login_at") `);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "patient_code" character varying(20) NOT NULL DEFAULT ('P-' || lpad(nextval('patient_code_seq')::text, 6, '0')), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "middle_name" character varying(100), "birth_date" date, "gender" "public"."gender", "phone" character varying(32), "email" character varying(150), "address" character varying(500), "passport" character varying(50), "profession" character varying(150), "avatar" text, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_patients_code" ON "patients" ("patient_code") `);
        await queryRunner.query(`CREATE INDEX "idx_patients_passport" ON "patients" ("passport") `);
        await queryRunner.query(`CREATE INDEX "idx_patients_created_at" ON "patients" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_patients_phone" ON "patients" ("phone") `);
        await queryRunner.query(`CREATE TABLE "contracts" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "contract_number" character varying(100) NOT NULL, "organization" character varying(255), "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2c7b8f3a7b1acdd49497d83d0fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_contracts_number" ON "contracts" ("contract_number") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_transaction_type" AS ENUM('PAYMENT', 'REFUND')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method" AS ENUM('CASH', 'CARD', 'CONTRACT')`);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "payment_id" uuid NOT NULL, "type" "public"."payment_transaction_type" NOT NULL, "method" "public"."payment_method" NOT NULL, "amount" numeric(14,2) NOT NULL, "note" text, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payment_transactions_payment" ON "payment_transactions" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_transactions_created_method" ON "payment_transactions" ("created_at", "method") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_status" AS ENUM('PAID', 'PARTIALLY_PAID', 'UNPAID', 'REFUNDED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "receipt_number" character varying(30) NOT NULL, "idempotency_key" character varying(64), "patient_id" uuid NOT NULL, "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "paid_amount" numeric(14,2) NOT NULL DEFAULT '0', "remaining_amount" numeric(14,2) NOT NULL DEFAULT '0', "refunded_amount" numeric(14,2) NOT NULL DEFAULT '0', "method" "public"."payment_method" NOT NULL, "status" "public"."payment_status" NOT NULL, "contract_id" uuid, "note" text, "cancel_reason" character varying(500), "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_payments_receipt_number" ON "payments" ("receipt_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_payments_idempotency_key" ON "payments" ("idempotency_key") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_patient" ON "payments" ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_method" ON "payments" ("method") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_created_at" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "payment_items" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "payment_id" uuid NOT NULL, "service_id" uuid NOT NULL, "service_name" character varying(200) NOT NULL, "service_code" character varying(30) NOT NULL, "department_id" uuid NOT NULL, "doctor_id" uuid, "price" numeric(14,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "amount" numeric(14,2) NOT NULL, CONSTRAINT "PK_fd39b89ecfb988844dfee250f9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payment_items_department" ON "payment_items" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_items_doctor" ON "payment_items" ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_items_service" ON "payment_items" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_items_payment" ON "payment_items" ("payment_id") `);
        await queryRunner.query(`CREATE TABLE "queue_counters" ("queue_date" date NOT NULL, "prefix" character varying(3) NOT NULL, "last_number" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_73aaa57f2d95b044dc61c7efbd5" PRIMARY KEY ("queue_date", "prefix"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_status" AS ENUM('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "queue_tickets" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "ticket_number" character varying(12) NOT NULL, "prefix" character varying(3) NOT NULL, "sequence" integer NOT NULL, "queue_date" date NOT NULL, "status" "public"."queue_status" NOT NULL DEFAULT 'WAITING', "patient_id" uuid NOT NULL, "doctor_id" uuid, "department_id" uuid NOT NULL, "payment_id" uuid, "room_number" character varying(20), "called_at" TIMESTAMP WITH TIME ZONE, "called_count" integer NOT NULL DEFAULT '0', "called_by_id" uuid, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "cancel_reason" character varying(500), "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1b903aa90bcc04136caa6540c55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_queue_tickets_payment" ON "queue_tickets" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_queue_tickets_patient" ON "queue_tickets" ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_queue_tickets_date_status" ON "queue_tickets" ("queue_date", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_queue_tickets_doctor_date_status" ON "queue_tickets" ("doctor_id", "queue_date", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_queue_tickets_date_number" ON "queue_tickets" ("queue_date", "ticket_number") `);
        await queryRunner.query(`CREATE TABLE "queue_ticket_services" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "ticket_id" uuid NOT NULL, "service_id" uuid NOT NULL, "payment_item_id" uuid, "service_name" character varying(200) NOT NULL, CONSTRAINT "PK_d40007cb658d238cf8cd36c08c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_queue_ticket_services_ticket" ON "queue_ticket_services" ("ticket_id") `);
        await queryRunner.query(`CREATE TABLE "service_price_history" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "service_id" uuid NOT NULL, "old_price" numeric(14,2) NOT NULL, "new_price" numeric(14,2) NOT NULL, "changed_by_id" uuid, "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_86449126d733833cf85496584a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_service_price_history_service" ON "service_price_history" ("service_id", "changed_at") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("key" character varying(64) NOT NULL, "value" jsonb, "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b1b5bc664526d375c94ce9ad43d" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TYPE "public"."visit_status" AS ENUM('IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "visits" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "queue_ticket_id" uuid NOT NULL, "patient_id" uuid NOT NULL, "doctor_id" uuid NOT NULL, "status" "public"."visit_status" NOT NULL DEFAULT 'IN_PROGRESS', "started_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ended_at" TIMESTAMP WITH TIME ZONE, "complaint" text, "diagnosis" text, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_94ff907725194523b870b2b14a2" UNIQUE ("queue_ticket_id"), CONSTRAINT "REL_94ff907725194523b870b2b14a" UNIQUE ("queue_ticket_id"), CONSTRAINT "PK_0b0b322289a41015c6ea4e8bf30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_visits_doctor_started" ON "visits" ("doctor_id", "started_at") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_patient" ON "visits" ("patient_id") `);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_fe8dcab94e4095af071399c6523" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_services" ADD CONSTRAINT "FK_7332c5a1ffea02df1ef5c16c552" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_services" ADD CONSTRAINT "FK_8679bceaa0d0514f7e2a18ec12b" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kiosk_requests" ADD CONSTRAINT "FK_7876bd50d137a654b1667ea0b4e" FOREIGN KEY ("kiosk_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kiosk_requests" ADD CONSTRAINT "FK_b648fde90645e8e257e436e0b72" FOREIGN KEY ("processed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kiosk_request_items" ADD CONSTRAINT "FK_b7b51c8b4ed602ba2bc2cf79a5f" FOREIGN KEY ("kiosk_request_id") REFERENCES "kiosk_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kiosk_request_items" ADD CONSTRAINT "FK_c8955e414316828872d0601b405" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_history" ADD CONSTRAINT "FK_ad9ce49cb73c0b33746a56b6bd1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "FK_b48dc58a26594f4674191275477" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_1f4dd90aece142a3a591cf4334b" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_66ec1ff722bbb21d84ba4848e29" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_4d2ce22525e1801b449f24a9898" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_52fc2356fb8c211c93d4b1496f3" FOREIGN KEY ("contract_id") REFERENCES "contracts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_6a01849dbd3e28beb83ec16b577" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_items" ADD CONSTRAINT "FK_c03172d6a1edb318ab03bdbb883" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_items" ADD CONSTRAINT "FK_ec996972dc20e41af576c6da736" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_items" ADD CONSTRAINT "FK_035288755786598a276b3f77cc2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_items" ADD CONSTRAINT "FK_aeb8175f5ed3e9c81001d236914" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_e23ac161d017b9a5afeb5077e53" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_4d050f280422f3e0a2ff565637a" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_45a0850792d949769ef42829af5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_f55390884b64658152361ac2f0f" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" ADD CONSTRAINT "FK_05027e74c33f3e1aa792bbfe45d" FOREIGN KEY ("ticket_id") REFERENCES "queue_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" ADD CONSTRAINT "FK_05621fead09dfc19d9947194a10" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" ADD CONSTRAINT "FK_c9695904beb72c9879ace7c971d" FOREIGN KEY ("payment_item_id") REFERENCES "payment_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_price_history" ADD CONSTRAINT "FK_6387d5086c6893b87c0b695ce41" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_price_history" ADD CONSTRAINT "FK_58adcd0b72c9614d9198546e28f" FOREIGN KEY ("changed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_94ff907725194523b870b2b14a2" FOREIGN KEY ("queue_ticket_id") REFERENCES "queue_tickets"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_5054db93135a6d966fd3939caa6" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_b7464db829efa66fc3cd47de16a" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        // Search indexes (trigram) for patient lookup by name / phone / code
        await queryRunner.query(`CREATE INDEX "idx_patients_last_name_trgm" ON "patients" USING gin (lower("last_name") gin_trgm_ops)`);
        await queryRunner.query(`CREATE INDEX "idx_patients_first_name_trgm" ON "patients" USING gin (lower("first_name") gin_trgm_ops)`);
        await queryRunner.query(`CREATE INDEX "idx_patients_phone_trgm" ON "patients" USING gin ("phone" gin_trgm_ops)`);
        // Business constraints
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "chk_payments_amounts" CHECK ("total_amount" >= 0 AND "paid_amount" >= 0 AND "remaining_amount" >= 0 AND "refunded_amount" >= 0 AND "refunded_amount" <= "paid_amount")`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "chk_payment_transactions_amount" CHECK ("amount" > 0)`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "chk_services_price" CHECK ("price" >= 0)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT IF EXISTS "chk_services_price"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT IF EXISTS "chk_payment_transactions_amount"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "chk_payments_amounts"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "idx_patients_phone_trgm"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "idx_patients_first_name_trgm"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "idx_patients_last_name_trgm"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_b7464db829efa66fc3cd47de16a"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_5054db93135a6d966fd3939caa6"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_94ff907725194523b870b2b14a2"`);
        await queryRunner.query(`ALTER TABLE "service_price_history" DROP CONSTRAINT "FK_58adcd0b72c9614d9198546e28f"`);
        await queryRunner.query(`ALTER TABLE "service_price_history" DROP CONSTRAINT "FK_6387d5086c6893b87c0b695ce41"`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" DROP CONSTRAINT "FK_c9695904beb72c9879ace7c971d"`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" DROP CONSTRAINT "FK_05621fead09dfc19d9947194a10"`);
        await queryRunner.query(`ALTER TABLE "queue_ticket_services" DROP CONSTRAINT "FK_05027e74c33f3e1aa792bbfe45d"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_f55390884b64658152361ac2f0f"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_45a0850792d949769ef42829af5"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_4d050f280422f3e0a2ff565637a"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_e23ac161d017b9a5afeb5077e53"`);
        await queryRunner.query(`ALTER TABLE "payment_items" DROP CONSTRAINT "FK_aeb8175f5ed3e9c81001d236914"`);
        await queryRunner.query(`ALTER TABLE "payment_items" DROP CONSTRAINT "FK_035288755786598a276b3f77cc2"`);
        await queryRunner.query(`ALTER TABLE "payment_items" DROP CONSTRAINT "FK_ec996972dc20e41af576c6da736"`);
        await queryRunner.query(`ALTER TABLE "payment_items" DROP CONSTRAINT "FK_c03172d6a1edb318ab03bdbb883"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_6a01849dbd3e28beb83ec16b577"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_52fc2356fb8c211c93d4b1496f3"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_4d2ce22525e1801b449f24a9898"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_66ec1ff722bbb21d84ba4848e29"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_1f4dd90aece142a3a591cf4334b"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "FK_b48dc58a26594f4674191275477"`);
        await queryRunner.query(`ALTER TABLE "login_history" DROP CONSTRAINT "FK_ad9ce49cb73c0b33746a56b6bd1"`);
        await queryRunner.query(`ALTER TABLE "kiosk_request_items" DROP CONSTRAINT "FK_c8955e414316828872d0601b405"`);
        await queryRunner.query(`ALTER TABLE "kiosk_request_items" DROP CONSTRAINT "FK_b7b51c8b4ed602ba2bc2cf79a5f"`);
        await queryRunner.query(`ALTER TABLE "kiosk_requests" DROP CONSTRAINT "FK_b648fde90645e8e257e436e0b72"`);
        await queryRunner.query(`ALTER TABLE "kiosk_requests" DROP CONSTRAINT "FK_7876bd50d137a654b1667ea0b4e"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427"`);
        await queryRunner.query(`ALTER TABLE "doctor_services" DROP CONSTRAINT "FK_8679bceaa0d0514f7e2a18ec12b"`);
        await queryRunner.query(`ALTER TABLE "doctor_services" DROP CONSTRAINT "FK_7332c5a1ffea02df1ef5c16c552"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_fe8dcab94e4095af071399c6523"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_patient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_doctor_started"`);
        await queryRunner.query(`DROP TABLE "visits"`);
        await queryRunner.query(`DROP TYPE "public"."visit_status"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_service_price_history_service"`);
        await queryRunner.query(`DROP TABLE "service_price_history"`);
        await queryRunner.query(`DROP INDEX "public"."idx_queue_ticket_services_ticket"`);
        await queryRunner.query(`DROP TABLE "queue_ticket_services"`);
        await queryRunner.query(`DROP INDEX "public"."uq_queue_tickets_date_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_queue_tickets_doctor_date_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_queue_tickets_date_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_queue_tickets_patient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_queue_tickets_payment"`);
        await queryRunner.query(`DROP TABLE "queue_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."queue_status"`);
        await queryRunner.query(`DROP TABLE "queue_counters"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_items_payment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_items_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_items_doctor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_items_department"`);
        await queryRunner.query(`DROP TABLE "payment_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_method"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_patient"`);
        await queryRunner.query(`DROP INDEX "public"."uq_payments_idempotency_key"`);
        await queryRunner.query(`DROP INDEX "public"."uq_payments_receipt_number"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_transactions_created_method"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_transactions_payment"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transaction_type"`);
        await queryRunner.query(`DROP INDEX "public"."uq_contracts_number"`);
        await queryRunner.query(`DROP TABLE "contracts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_passport"`);
        await queryRunner.query(`DROP INDEX "public"."uq_patients_code"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP INDEX "public"."idx_login_history_user_login_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_login_history_login_at"`);
        await queryRunner.query(`DROP TABLE "login_history"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kiosk_request_items_request"`);
        await queryRunner.query(`DROP TABLE "kiosk_request_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kiosk_requests_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."uq_kiosk_requests_number"`);
        await queryRunner.query(`DROP TABLE "kiosk_requests"`);
        await queryRunner.query(`DROP TYPE "public"."kiosk_request_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_module_action"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_users_login"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."gender"`);
        await queryRunner.query(`DROP TYPE "public"."user_status"`);
        await queryRunner.query(`DROP TYPE "public"."user_role"`);
        await queryRunner.query(`DROP TABLE "doctors"`);
        await queryRunner.query(`DROP INDEX "public"."uq_doctor_services_pair"`);
        await queryRunner.query(`DROP INDEX "public"."idx_doctor_services_service"`);
        await queryRunner.query(`DROP TABLE "doctor_services"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_department_active"`);
        await queryRunner.query(`DROP INDEX "public"."uq_services_code"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "public"."uq_departments_queue_prefix"`);
        await queryRunner.query(`DROP INDEX "public"."uq_departments_code"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP SEQUENCE IF EXISTS "receipt_number_seq"`);
        await queryRunner.query(`DROP SEQUENCE IF EXISTS "kiosk_request_number_seq"`);
        await queryRunner.query(`DROP SEQUENCE IF EXISTS "patient_code_seq"`);
    }

}
