import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Gender } from '../../../common/constants/enums';
import { User } from '../../users/entities/user.entity';

@Entity('patients')
/** GIN trigram indexes are created in the migration (expression indexes TypeORM cannot model). */
@Index('idx_patients_phone_trgm', { synchronize: false })
@Index('idx_patients_last_name_trgm', { synchronize: false })
@Index('idx_patients_first_name_trgm', { synchronize: false })
@Index('idx_patients_phone', ['phone'])
@Index('idx_patients_created_at', ['createdAt'])
@Index('idx_patients_passport', ['passport'])
export class Patient {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Human readable id, generated by the DB from `patient_code_seq` (e.g. P-000123). */
  @Index('uq_patients_code', { unique: true })
  @Column({
    length: 20,
    default: () => "('P-' || lpad(nextval('patient_code_seq')::text, 6, '0'))",
  })
  patientCode: string;

  @Column({ length: 100 })
  firstName: string;

  @Column({ length: 100 })
  lastName: string;

  @Column({ type: 'varchar', length: 100, nullable: true })
  middleName: string | null;

  @Column({ type: 'date', nullable: true })
  birthDate: string | null;

  @Column({ type: 'enum', enum: Gender, enumName: 'gender', nullable: true })
  gender: Gender | null;

  @Column({ type: 'varchar', length: 32, nullable: true })
  phone: string | null;

  @Column({ type: 'varchar', length: 150, nullable: true })
  email: string | null;

  @Column({ type: 'varchar', length: 500, nullable: true })
  address: string | null;

  @Column({ type: 'varchar', length: 50, nullable: true })
  passport: string | null;

  @Column({ type: 'varchar', length: 150, nullable: true })
  profession: string | null;

  @Column({ type: 'text', nullable: true })
  avatar: string | null;

  @Column({ type: 'uuid', nullable: true })
  createdById: string | null;

  @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'created_by_id' })
  createdBy?: User | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;
}
